Part A – Data Extraction

Task 1

In [109]:
import pandas as pd

In [110]:
population = pd.read_csv('/content/population.csv')

In [111]:
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [112]:
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [113]:
population.shape

(25, 2)

In [114]:
population.dtypes

country       object
population     int64
dtype: object

Task 2

In [115]:
gdp = pd.read_excel('/content/gdp.xlsx')
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [116]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [117]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

Task 3

In [118]:
internet_users = pd.read_json('internet_users.json')

In [119]:
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [120]:
internet_users = pd.DataFrame(internet_users)

In [121]:
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

Task 4

In [122]:
literacy_rate = pd.read_xml('/content/literacy_rate.xml')
literacy_rate

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [123]:
df = pd.DataFrame(literacy_rate)
df

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Part B - Data Understanding

Task 5

In [124]:
#gdp

Num_of_rows = len(gdp)
Num_of_rows

25

In [125]:
Num_of_columns = len(gdp.columns)
Num_of_columns

2

In [126]:
gdp.shape

(25, 2)

In [127]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [128]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [129]:
missing_value = gdp.isnull().sum()
missing_value

Country    0
GDP        0
dtype: int64

In [130]:
duplicate_records = gdp.duplicated().sum()
duplicate_records

np.int64(0)

In [131]:
#population
len(population)

25

In [132]:
len(population.columns)

2

In [133]:
population.columns

Index(['country', 'population'], dtype='object')

In [134]:
population.dtypes

country       object
population     int64
dtype: object

In [135]:
population.isnull().sum()

country       0
population    0
dtype: int64

In [136]:
population.duplicated().sum()

np.int64(0)

In [137]:
# internet_users
len(internet_users)

25

In [138]:
len(internet_users.columns)

2

In [139]:
internet_users.columns

Index(['country', 'internet_users'], dtype='object')

In [140]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [141]:
internet_users.isnull().sum()

country           0
internet_users    0
dtype: int64

In [142]:
internet_users.duplicated().sum()

np.int64(0)

In [143]:
#literacy_rate
len(literacy_rate)

25

In [144]:
len(literacy_rate.columns)

2

In [145]:
literacy_rate.columns

Index(['name', 'literacy_rate'], dtype='object')

In [146]:
literacy_rate.dtypes

name              object
literacy_rate    float64
dtype: object

Part C

Task 6

In [147]:
#Rename columns wherever necessary so that all datasets have a common column name for merging

gdp = gdp.rename(columns={'Country': 'country'})
gdp

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [148]:
literacy_rate = literacy_rate.rename(columns={'name': 'country'})
literacy_rate

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Task 7

In [149]:
# Convert the required columns into appropriate numeric data types

population["population"] = pd.to_numeric(
    population["population"], errors="coerce"
)
gdp["GDP"] = pd.to_numeric(gdp["GDP"], errors="coerce")
internet_users["internet_users"] = pd.to_numeric(
    internet_users["internet_users"], errors="coerce"
)
literacy_rate["literacy_rate"] = pd.to_numeric(
    literacy_rate["literacy_rate"], errors="coerce"
)

In [150]:
population.dtypes

country       object
population     int64
dtype: object

In [151]:
gdp.dtypes

country    object
GDP         int64
dtype: object

In [152]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [153]:
literacy_rate.dtypes

country           object
literacy_rate    float64
dtype: object

Task 8

In [154]:
# Merge all four datasets into one DataFrame

merged = (
    population.merge(literacy_rate, on="country", how="inner")
    .merge(internet_users, on="country", how="inner")
    .merge(gdp, on="country", how="inner")
)

In [155]:
merged

           country  population  literacy_rate  internet_users       GDP
0    United States   331002651           99.0       312000000  30500000
1            China  1411778724           97.2      1080000000  19230000
2            India  1380004385           77.7       850000000   4187000
3            Japan   125836021           99.0       118000000   4180000
4          Germany    83240525           99.0        79000000   4744000
5   United Kingdom    67886011           99.0        66000000   3839000
6           France    65273511           99.0        62000000   3211000
7            Italy    60461826           99.0        56000000   2420000
8           Canada    38005238           99.0        36000000   2250000
9        Australia    25687041           99.0        24000000   1880000
10          Brazil   212559417           93.2       181000000   2330000
11          Russia   145934462           99.7       125000000   2200000
12     South Korea    51780579           98.8        50000000   1800000
13           Spain    46754778           98.6        44000000   1710000
14          Mexico   128932753           95.4       102000000   1810000
15       Indonesia   273523615           96.0       212000000   1500000
16    Saudi Arabia    34813871           97.3        34000000   1100000
17          Turkey    84339067           96.7        69000000   1350000
18    South Africa    59308690           95.0        43000000    410000
19       Argentina    45195774           99.1        41000000    640000
20     Netherlands    17441139           99.0        17000000   1150000
21     Switzerland     8654622           99.0         8500000    940000
22          Sweden    10353442           99.0        10100000    650000
23          Norway     5421241          100.0         5300000    580000
24       Singapore     5850342           97.5         5600000    530000

Task 9

In [156]:
# Create the following calculated columns:

# 1. Internet Penetration (%)
# 2. GDP Per Capita

In [157]:
merged["internet_penetration (%)"] = (
    merged["internet_users"] / merged["population"] * 100
).round(2)

In [158]:
merged["GDP_Per_Capita"] = (
    merged["GDP"] * 1000000 / merged["population"]
).round(2)

In [159]:
merged

,country,population,literacy_rate,internet_users,GDP,internet_penetration (%),GDP_Per_Capita
0,United States,331002651,99.0,312000000,30500000,94.26,92144.28
1,China,1411778724,97.2,1080000000,19230000,76.50,13621.11
2,India,1380004385,77.7,850000000,4187000,61.59,3034.05
3,Japan,125836021,99.0,118000000,4180000,93.77,33217.83
4,Germany,83240525,99.0,79000000,4744000,94.91,56991.47
5,United Kingdom,67886011,99.0,66000000,3839000,97.22,56550.68
6,France,65273511,99.0,62000000,3211000,94.98,49193.00
7,Italy,60461826,99.0,56000000,2420000,92.62,40025.25
8,Canada,38005238,99.0,36000000,2250000,94.72,59202.37
9,Australia,25687041,99.0,24000000,1880000,93.43,73188.66
10,Brazil,212559417,93.2,181000000,2330000,85.15,10961.64
11,Russia,145934462,99.7,125000000,2200000,85.65,15075.26
12,South Korea,51780579,98.8,50000000,1800000,96.56,34762.07
13,Spain,46754778,98.6,44000000,1710000,94.11,36573.80
14,Mexico,128932753,95.4,102000000,1810000,79.11,14038.33
15,Indonesia,273523615,96.0,212000000,1500000,77.51,5483.99
16,Saudi Arabia,34813871,97.3,34000000,1100000,97.66,31596.60
17,Turkey,84339067,96.7,69000000,1350000,81.81,16006.82
18,South Africa,59308690,95.0,43000000,410000,72.50,6912.98
19,Argentina,45195774,99.1,41000000,640000,90.72,14160.62
20,Netherlands,17441139,99.0,17000000,1150000,97.47,65936.06
21,Switzerland,8654622,99.0,8500000,940000,98.21,108612.48
22,Sweden,10353442,99.0,10100000,650000,97.55,62781.05
23,Norway,5421241,100.0,5300000,580000,97.76,106986.57
24,Singapore,5850342,97.5,5600000,530000,95.72,90592.99

Part D - Load Data

Task 10

In [185]:
import sqlite3

In [190]:
conn =sqlite3.connect("country_statistics.db")

In [197]:
conn =sqlite3.connect("country_statistics.db")
merged.to_sql("country_statistics",conn,
              if_exists = "replace",
              index = False
              )
conn.close()

In [193]:
df = pd.read_sql("SELECT * FROM country_statistics", conn)
df

,country,population,literacy_rate,internet_users,GDP,internet_penetration (%),GDP_Per_Capita
0,United States,331002651,99.0,312000000,30500000,94.26,92144.28
1,China,1411778724,97.2,1080000000,19230000,76.50,13621.11
2,India,1380004385,77.7,850000000,4187000,61.59,3034.05
3,Japan,125836021,99.0,118000000,4180000,93.77,33217.83
4,Germany,83240525,99.0,79000000,4744000,94.91,56991.47
5,United Kingdom,67886011,99.0,66000000,3839000,97.22,56550.68
6,France,65273511,99.0,62000000,3211000,94.98,49193.00
7,Italy,60461826,99.0,56000000,2420000,92.62,40025.25
8,Canada,38005238,99.0,36000000,2250000,94.72,59202.37
9,Australia,25687041,99.0,24000000,1880000,93.43,73188.66
10,Brazil,212559417,93.2,181000000,2330000,85.15,10961.64
11,Russia,145934462,99.7,125000000,2200000,85.65,15075.26
12,South Korea,51780579,98.8,50000000,1800000,96.56,34762.07
13,Spain,46754778,98.6,44000000,1710000,94.11,36573.80
14,Mexico,128932753,95.4,102000000,1810000,79.11,14038.33
15,Indonesia,273523615,96.0,212000000,1500000,77.51,5483.99
16,Saudi Arabia,34813871,97.3,34000000,1100000,97.66,31596.60
17,Turkey,84339067,96.7,69000000,1350000,81.81,16006.82
18,South Africa,59308690,95.0,43000000,410000,72.50,6912.98
19,Argentina,45195774,99.1,41000000,640000,90.72,14160.62
20,Netherlands,17441139,99.0,17000000,1150000,97.47,65936.06
21,Switzerland,8654622,99.0,8500000,940000,98.21,108612.48
22,Sweden,10353442,99.0,10100000,650000,97.55,62781.05
23,Norway,5421241,100.0,5300000,580000,97.76,106986.57
24,Singapore,5850342,97.5,5600000,530000,95.72,90592.99

Task 11

In [214]:
def load_imdb_database(db_path):
  try:
    conn = sqlite3.connect(db_path)
    print("IMDB database loaded successfully.")
    return conn
  except sqlite3.Error as e:
    print(f"Error loading IMDB database: {e}")
    return None

In [217]:
db_path = "country_statistics .db"
conn = load_imdb_database(db_path)

if conn:
  print("Connection successful")
  cursor = conn.cursor()

IMDB database loaded successfully.
Connection successful

In [218]:
df.head()

,country,population,literacy_rate,internet_users,GDP,internet_penetration (%),GDP_Per_Capita
0,United States,331002651,99.0,312000000,30500000,94.26,92144.28
1,China,1411778724,97.2,1080000000,19230000,76.50,13621.11
2,India,1380004385,77.7,850000000,4187000,61.59,3034.05
3,Japan,125836021,99.0,118000000,4180000,93.77,33217.83
4,Germany,83240525,99.0,79000000,4744000,94.91,56991.47

Part E - Data Analysis Using Pandas

In [164]:
# 1
merged.nlargest(5,"GDP")[['country','GDP']]

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [165]:
# 2
merged.nlargest(5,"population")[['country','population']]

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [166]:
#3
merged['literacy_rate'].mean()

np.float64(97.248)

In [167]:
#4
merged[merged['literacy_rate']>90][['country','literacy_rate' ]]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [168]:
# 5
merged[merged['internet_penetration (%)']>90][['country','internet_penetration (%)' ]]

           country  internet_penetration (%)
0    United States                     94.26
3            Japan                     93.77
4          Germany                     94.91
5   United Kingdom                     97.22
6           France                     94.98
7            Italy                     92.62
8           Canada                     94.72
9        Australia                     93.43
12     South Korea                     96.56
13           Spain                     94.11
16    Saudi Arabia                     97.66
19       Argentina                     90.72
20     Netherlands                     97.47
21     Switzerland                     98.21
22          Sweden                     97.55
23          Norway                     97.76
24       Singapore                     95.72

In [169]:
#6
merged.nlargest(5, "GDP_Per_Capita")[["country","GDP_Per_Capita"]]

          country  GDP_Per_Capita
21    Switzerland       108612.48
23         Norway       106986.57
0   United States        92144.28
24      Singapore        90592.99
9       Australia        73188.66

In [170]:
#7
merged['population'].sum()

np.int64(4720039725)

In [171]:
#8
merged['internet_penetration (%)'].mean()

np.float64(89.6596)

In [172]:
# 9
merged.loc[merged["internet_users"].idxmax(),['country','internet_users']]

country                China
internet_users    1080000000
Name: 1, dtype: object

In [173]:
# 10
merged['literacy_rate'].corr(merged['internet_penetration (%)'])

np.float64(0.77279756813985)

Part F - Data Analysis using SQL

In [198]:
conn=sqlite3.connect('country_statistics.db')

In [204]:
#11
pd.read_sql("""
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5
""", conn)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [207]:
#12
pd.read_sql("""
SELECT AVG(literacy_rate) AS
average_litracy_rate
from country_statistics
""", conn)

   average_litracy_rate
0                97.248

In [208]:
#13
pd.read_sql(
    """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90
ORDER BY literacy_rate DESC
""",
    conn,
)

           country  literacy_rate
0           Norway          100.0
1           Russia           99.7
2        Argentina           99.1
3    United States           99.0
4            Japan           99.0
5          Germany           99.0
6   United Kingdom           99.0
7           France           99.0
8            Italy           99.0
9           Canada           99.0
10       Australia           99.0
11     Netherlands           99.0
12     Switzerland           99.0
13          Sweden           99.0
14     South Korea           98.8
15           Spain           98.6
16       Singapore           97.5
17    Saudi Arabia           97.3
18           China           97.2
19          Turkey           96.7
20       Indonesia           96.0
21          Mexico           95.4
22    South Africa           95.0
23          Brazil           93.2

In [209]:
#14
pd.read_sql(
    """
SELECT country, `internet_penetration (%)`
FROM country_statistics
ORDER BY `internet_penetration (%)` DESC
LIMIT 5
""",
    conn,
)

        country  internet_penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

In [178]:
#15
pd.read_sql(
    """
SELECT SUM(population) AS total_population
FROM country_statistics
""",
    conn,
)

   total_population
0        4720039725

In [179]:
#16
pd.read_sql(
    """
SELECT country, GDP_Per_Capita
FROM country_statistics
ORDER BY GDP_Per_Capita DESC
LIMIT 1
""",
    conn,
)

       country  GDP_Per_Capita
0  Switzerland       108612.48

In [180]:
#17
merged.to_csv("country_statistics.csv", index=False)

In [210]:
#18

pd.read_sql(
    """
SELECT country, GDP_Per_Capita
FROM country_statistics
ORDER BY GDP_Per_Capita DESC
LIMIT 10
""",
    conn,
)

          country  GDP_Per_Capita
0     Switzerland       108612.48
1          Norway       106986.57
2   United States        92144.28
3       Singapore        90592.99
4       Australia        73188.66
5     Netherlands        65936.06
6          Sweden        62781.05
7          Canada        59202.37
8         Germany        56991.47
9  United Kingdom        56550.68

#### Write a short summary (5–6 points) explaining your ETL process, including:

*   Data sources used : Data was collected from four different sources - GDP data from gdp.xlsx, internet usage data from internet_users.json, literacy rate data from literacy_rate.xml, and population data from population.csv.

*   Data cleaning steps : The datasets were checked for missing values, duplicate records, incorrect data types, and unnecessary fields. The data was cleaned to ensure consistency and accuracy.

*   Transformations performed : Required fields were extracted from each file and converted into DataFrames. Column names and data types were standardized, and the datasets were prepared for analysis.

*   Database Loading Process: The cleaned and transformed data was loaded into the SQL database using appropriate tables and columns. SQL queries were then used to retrieve and analyze the data.

*   Key insights obtained from the analysis: The analysis helped identify countries with high GDP per Capita, population trends, literacy rates, and internet usage, including the top 10 countries based on GDP per Capita.